### PR TITLE
1039 feature add customized dropdown menu on user event create page

### PR DESCRIPTION
**Pull request by bingzhang**
## Description
_Please provide a summary of the pull request and the issue it fixes. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Fixes #(add issue number here and remove parentheses)**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [ ] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
Please update changelog.

In user events /edit and /add pages, the Save / Add button disabled style is different from zeplin design. I think this PR deals with disabled button styles as well. Hence checking that here. But would be good to put in the PR description / the issue what this PR actually changes.
Screen Shot 2023-02-21 at 1 03 31 PM
Screen Shot 2023-02-21 at 1 06 08 PM

In /event/add page, when you choose Category "Athletics", the subcategory displays disabled but you can actually click the dropdown menu. Maybe it should not display "(disabled)" in the placeholder.

The dropdown menu styling in /add page looks good.

**Comment by sandeep-ps** [comment]
1. Before selecting an item from the drop-down, it looks similar to a disabled drop-down. I missed this when reviewing the edit page. The below screenshot from the design shows both how the help text needs to appear before a user selects an item (first design) and later when they have selected an item (second design):
3. image
4. When a user selects the Athletics category, the subcategories drop-down should become enabled, and the text needs to change to  "Choose an event subcategory..." and when the user switches to a non-athletics category, the subcategory needs to become disabled with text changing to "Choose an event subcategory (disabled) ..." This previous behavior seems to have changed with the new implementation. I missed this one, too, with the edit PR review.
5. Please update the CHANGELOG and mention all issues linked to this PR (like Minu suggested above).

**Comment by bingzhang** [comment]
> Please update changelog.
> 
> In user events /edit and /add pages, the Save / Add button disabled style is different from zeplin design. I think this PR deals with disabled button styles as well. Hence checking that here. But would be good to put in the PR description / the issue what this PR actually changes. Screen Shot 2023-02-21 at 1 03 31 PM Screen Shot 2023-02-21 at 1 06 08 PM
> 
> In /event/add page, when you choose Category "Athletics", the subcategory displays disabled but you can actually click the dropdown menu. Maybe it should not display "(disabled)" in the placeholder.
> 
> The dropdown menu styling in /add page looks good.

@minump this pr has nothing to do with the button. it is dropdown menu on create page.

**Comment by bingzhang** [comment]
> 3\. Choose an event subcategory..

1 the design is not appropriate. We already have the category label on the left. In this pr, we follow the previous design.

**Comment by bingzhang** [comment]
> Please update changelog.
> 
> In user events /edit and /add pages, the Save / Add button disabled style is different from zeplin design. I think this PR deals with disabled button styles as well. Hence checking that here. But would be good to put in the PR description / the issue what this PR actually changes. Screen Shot 2023-02-21 at 1 03 31 PM Screen Shot 2023-02-21 at 1 06 08 PM
> 
> In /event/add page, when you choose Category "Athletics", the subcategory displays disabled but you can actually click the dropdown menu. Maybe it should not display "(disabled)" in the placeholder.
> 
> The dropdown menu styling in /add page looks good.

what is the meaning of the blue underline in the browser url?

**Comment by minump** [comment]
> > Please update changelog.
> > In user events /edit and /add pages, the Save / Add button disabled style is different from zeplin design. I think this PR deals with disabled button styles as well. Hence checking that here. But would be good to put in the PR description / the issue what this PR actually changes. Screen Shot 2023-02-21 at 1 03 31 PM Screen Shot 2023-02-21 at 1 06 08 PM
> > In /event/add page, when you choose Category "Athletics", the subcategory displays disabled but you can actually click the dropdown menu. Maybe it should not display "(disabled)" in the placeholder.
> > The dropdown menu styling in /add page looks good.
> 
> what is the meaning of the blue underline in the browser url?

Just wanted to highlight the url / edit. Nothing much.
Was confused on what to test for in this PR.

As for the dropdown menu - it looks good to me, except for the subcategory being disabled issue in Athletics category.

**Comment by sandeep-ps** [comment]
> > 3. Choose an event subcategory..
> 
> 1 the design is not appropriate. We already have the category label on the left. In this pr, we follow the previous design.

Please note that there is a grey background color in the implementation for active drop-downs, while it's not in the design. With the current change, it won't be possible to differentiate between active and disabled drop-downs. Please let me know if you prefer to chat about this. Thanks.

image

**Comment by sandeep-ps** [comment]
Hi, Bing, The active drop-down menu changes look fine, but the disabled drop-down menu also has changed now (I think that should have stayed grey for differentiating between active and disabled elements). Anyway, I have added a question about getting a design for disabled input fields. I will approve this PR. 

Minu, when you get a chance, please share your feedback too. Thanks.

**Review by sandeep-ps — APPROVED** [review]

**Comment by minump** [comment]
Two minor things which I think can be fixed in separate issues.
1. When the dropdown menu is opened, and the user clicks outside of the dropdown menu, the dropdown menu ideally should close. But it doesnt in the current implementation.
Screen Shot 2023-02-23 at 2 58 31 PM
2. The subcategory display was "Choose subcategory (disabled)" when the category was something other than "Athletics". But now the subcategory is "None" for all categories.

**Comment by minump** [comment]
Minor font changes on hover (font-weight bold and hover color) can be changed in the fine-tuning process.
Approving the PR.

**Review by minump — APPROVED** [review]
Approved

**Pull request merged**
