### PR TITLE
801 subevent linked one superevent

### LINKED ISSUE #801: [BUG] Subevent linked to only one superevent
**Describe the bug**
Subevent stores only one superEventId. If the same event is a subevent for multiple super events, the latest superEventId is over-written to the field.

**To Reproduce**
1. Create an event (Eg: subeventA)
2. Create 2 superevents (Eg: supereventAA and supereventAAA)
3. Link subevent to both superevents
4. Only the latest link is reflected in the superEventId field of the subevent.

**Expected behavior**
Subevent can be a part of multiple super events. Change the superEventId field to an array instead of string.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by minump**
## Description
Currently a subevent is linked with only one superevent. The superEventID field is overwritten when the same subevent is linked to another super event. This replaces the superEventID field to be an array.

**Fixes #801**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [x] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [ ] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by minump** [comment]
superEventID should be backwards compatible. Check if superEventID is s string field or an array. Converted PR to draft to make these changes.

**Comment by bingzhang** [comment]
As I remember, our users only need to attach to one super event. Is there a new feature to add?

**Comment by minump** [comment]
> As I remember, our users only need to attach to one super event. Is there a new feature to add?

The users could add multiple subevents to one super event. However, in the subevent, only the latest superEventID is reflected.

**Comment by sandeep-ps** [comment]
This might need more discussion. Let's put this on hold for the time being.

**Comment by minump** [comment]
converting to draft as need more information on whether same subevent can be part of multiple super events.

**Pull request closed without merging**
