### PR TITLE
fix scheduler to take input from setting page

### PR DESCRIPTION
**Pull request by bingzhang**
## Description
_Please provide a summary of the pull request and the issue it fixes. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Fixes #(add issue number here and remove parentheses)**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [ ] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

### CODE REVIEW

**Comment by sandeep-ps** [comment]
Hi, @bingzhang, Thanks. I have feedback on a few items:

1. Please update the pull request description to fill in the checklist entries. This information will be helpful for all reviewers (current or new). Thanks.
2. Please update the settings page text about download scheduling to include details about the timezone. Here is a suggestion: `Events from these calendars will be crawled, parsed, and published daily at the scheduled time displayed below. The default scheduled time is 11:00 PM (Central Time). You can set a different time below.`
3. When I tried changing the time using the **develop** branch, it's working locally. With the change in this PR, a PytzUsageWarning warning about the timezone goes away. So, it's definitely an improvement, but to test if this would fix the actual problem, this will need to be deployed to the DEV instance.
4. After I set the time using the Settings page and restarting Events Manager (consider the example of container restarting due to some reason), Events Manager picks up the value in the environment and not the user input that's in the database. I think the core issue is that the Events Manager needs to prefer the user setting over the environment variable setting. Please fix this. Thanks.

**Review by sandeep-ps — CHANGES_REQUESTED** [review]
Provided feedback in a separate comment.

**Comment by bingzhang** [comment]
> Hi, @bingzhang, Thanks. I have feedback on a few items:
> 
> 1. Please update the pull request description to fill in the checklist entries. This information will be helpful for all reviewers (current or new). Thanks.
> 2. Please update the settings page text about download scheduling to include details about the timezone. Here is a suggestion: `Events from these calendars will be crawled, parsed, and published daily at the scheduled time displayed below. The default scheduled time is 11:00 PM (Central Time). You can set a different time below.`
> 3. When I tried changing the time using the **develop** branch, it's working locally. With the change in this PR, a PytzUsageWarning warning about the timezone goes away. So, it's definitely an improvement, but to test if this would fix the actual problem, this will need to be deployed to the DEV instance.
> 4. After I set the time using the Settings page and restarting Events Manager (consider the example of container restarting due to some reason), Events Manager picks up the value in the environment and not the user input that's in the database. I think the core issue is that the Events Manager needs to prefer the user setting over the environment variable setting. Please fix this. Thanks.

@sandeep-ps I updated the pr. I created a new issue related to your comments. https://github.com/rokwire/events-manager/issues/1035

**Review by sandeep-ps — APPROVED** [review]
Approving for further testing after deployment. Thanks.

**Review by minump — DISMISSED** [review]
LGTM

**Review by clav1d — APPROVED** [review]
The conflict fix looks good.

**Pull request merged**
