### PR TITLE
Hide past event

### LINKED ISSUE #587: [FEATURE] Filter to show or hide events that have passed
**Is your feature request related to a problem? Please describe.**
a checkbox on GUI, when checked, it will filter out events passed (the enddate is before today).

only the satisfied events will show on the GUI page.

### PR DESCRIPTION
**Pull request by clav1d**
close #587

### CODE REVIEW

**Comment by clav1d** [comment]
Currently, the hide past event checkbox will hide the event without an end date as well. Should we keep this behavior? @bingzhang @sandeep-ps

**Comment by sandeep-ps** [comment]
I think the number of user events created through Events Manager without an end date will be very small. So, let's continue to display those events without end date for now. Please only hide those events with end date less than today (i.e., any event that ended yesterday or before should not be displayed if that checkbox is selected.) @bingzhang, what do you think?

**Comment by bingzhang** [comment]
> I think the number of user events created through Events Manager without an end date will be very small. So, let's continue to display those events without end date for now. Please only hide those events with end date less than today (i.e., any event that ended yesterday or before should not be displayed if that checkbox is selected.) @bingzhang, what do you think?

I agree. That is what I and @clav1d discussed.

**Comment by bingzhang** [comment]
@clav1d right now, the evetns does not have enddate will not be displayed. Can update the code as what we discussed?

**Review by bingzhang — APPROVED** [review]

**Pull request merged**
