### PR TITLE
Various UI update

### LINKED ISSUE #651: [FEATURE] Move Events per page to the right of the Reset button
#641

### LINKED ISSUE #652: [FEATURE] Move the Create Event button to the title bar
#641

### LINKED ISSUE #653: [FEATURE] Update date format to MM-DD-YYYY HH:MM AM/PM on user event browse page
#641

### LINKED ISSUE #654: [FEATURE] Reduce font size to show more content on user event browse page.
#641

### PR DESCRIPTION
**Pull request by clav1d**
closes #654
closes #653
closes #652
closes #651

### CODE REVIEW

**Comment by bingzhang** [comment]
@clav1d the create button shows on the campus event page too.

**Comment by bingzhang** [comment]
and the need to resolve the merge conflicts after we merge the other prs.

**Comment by clav1d** [comment]
> @clav1d the create button shows on the campus event page too.

I don't have access to that so I cannot test it, but I'll try to fix it.

**Comment by clav1d** [comment]
> @clav1d the create button shows on the campus event page too.

This should have been fixed

**Review by bingzhang — APPROVED** [review]

**Pull request merged**
